### PR TITLE
Ext ids

### LINKED ISSUE #137: Service availability: external Ids
Right now, lighterpack uses a newline-delimited file for its "external Ids". These are the Ids that show up in the URL when sharing a list.

We're running out of the original list of external Ids. We could generate a new list (would need a script that checks for uniqueness against the existing database), or come up with a different solution to generating or storing these Ids.

### PR DESCRIPTION
**Pull request by colinmxs**
Fixes #137

### CODE REVIEW

**Comment by colinmxs** [comment]
just found this in the shortid repo:

https://github.com/dylang/shortid/pull/135/files

Looks like the project has been abandoned. I'll work on replacing the shortid usage with nanoid if this approach gels with you, @galenmaly

**Comment by galenmaly** [comment]
Sure, nanoid works! I'm normally wary of new dependencies but nanoid doesn't have any dependencies itself so it looks safe to use.

Let's configure it to use only lower case and numbers - no upper case or symbols - and to use ids with 6 characters like the existing IDs. Work for you?

**Comment by colinmxs** [comment]
Sounds great. I'll get this updated today or tomorrow. Thanks!

**Comment by colinmxs** [comment]
@galenmaly sorry to be pesky! Is this good to go?

**Comment by benkenawell** [comment]
I've been looking at this code, and trying find time to dive deep into vue (and mongodb) so I can help contribute.  But I was able to pull this branch down and play with it.  I think it's a good implementation!  Of course, I don't have any power to do anything about your PR, but bump it again so @galenmaly sees it.

**Comment by galenmaly** [comment]
Thanks @colinmxs !

**Pull request merged**
