### PR TITLE
Price column feature

### PR DESCRIPTION
**Pull request by martinzirkle**
This is my initial idea of adding the price feature column. Very simple, but the base for expanding to features like price per ounce & total pack cost. Would like to add the ability to set currency type. 

(I havent used git in a while, looks like working on windows here it added blank lines to some of the files. Let me know if there is a way to avoid this. Also I'm new to LESS but it seemed to generate a ton of extra lines for me when compiling common.less)

### CODE REVIEW

**Comment by galenmaly** [comment]
Thanks for building this out! I'm currently on vacation ( https://lighterpack.com/r/c036b5 ) and won't be able to review this for 2 weeks.  Feel free to ping me again then. 

As a FYI, one of the reasons I hadn't built this yet was because I was avoiding adding too much to the UI which can cause clutter. I want to build the functionality to have optional fields/columns so people can pick and choose what they want displayed. So depending on the UI you've built,  I might try and rush out that feature to allow this to go through.

**Comment by martinzirkle** [comment]
No rush on the review! I agree I wasn't exactly sure how to build this out and keep the UI minimal and yet useful.  Perhaps we should build out the optional columns feature first, and then build this in.  I'm okay if my branch doesn't get used, I had fun relearning git and learning some new code that I don't get to use at work.

**Comment by possibly** [comment]
@galenmaly @martinzirkle 

Status?

**Comment by galenmaly** [comment]
I refreshed the UI of LighterPack a bit to allow optional fields and have merged this commit in. Thanks for your contributions and apologies for the delay!

Before deploying this I'll need to:
1) Add price to new optionalFields list, defaulted to off
2) Add price unit (to new settings dropdown?)
3) Do a general QA pass, mainly on my changes.

Aiming for having this out within the next week, hopefully more like the next couple days.

Future nice-to-haves:
1) Users should be able to display the price breakdown in the pie chart/subtotals section up top.

**Comment by johnabela** [comment]
> Add price unit (to new settings dropdown?)

Nah, no need to go to the effort of that, just handle currencies in the same method as g/oz/lb/kg with a dropdown (lpUnitDropdown)

That would probably need to be hardcoded on just the creation page, and unlike on the WeightUnit, not have the lpUnitDropdown on the /r/ page, as doing that would mean you would have to code in currency exchange api.

An issue I can see coming up regarding price is how to handle items that might be alpha/beta/proto gear, T&E, sponsored gear, gifts, and such. These may not have integer/currencies values ($€xxx.xx) but instead need to be text/alpha-only strings. It would be nice to be able to use the PriceSubtotal field for recording of this information. So that could screw with the calculations if you are not willing to check for int() during the process.

**Comment by galenmaly** [comment]
I have added price as an optional field and added in a currency unit for price, currently looking to deploy sometime in the next day. Feel free to pull down the changes and let me know if you have any feedback.

**Pull request merged**
