### PR TITLE
Run local code with Vagrant

### PR DESCRIPTION
**Pull request by kurtabersold**
- Vagrantfile in root dir
- Inline script in Vagrantfile
- Code runs from localhost (rather than doing another git clone in the VM guest)
  - This allows you to edit code on your local machine
- App runs under nodemon; automatically restarts when changes are detected
  - js, mustache, and json files are watched for edits
  - files in ./public are ignored
- VM guest using Ubuntu 16.04
- Added systemd unit file to run app
- Changed .gitignore for vagrant log and run dir

### CODE REVIEW

**Comment by kurtabersold** [comment]
Maybe uninvited, but it would be great to be able to edit the code on my local machine, and have the change take affect in the VM automatically.

**Comment by galenmaly** [comment]
Thanks for submitting this! I don't use Vagrant so I won't be too knowledgeable about this change - but I do have a couple questions:

1) The only purpose for the init folder is for vagrant, so why not leave the vagrant files in the vagrant folder?
2) Does your new usage of vagrant need this new dependency or is that orthogonal to the vagrant change?

Thanks!

**Comment by kurtabersold** [comment]
1. This is probably just a workflow/preference thing. If it's a deal-breaker for you, I will move it back, but because the init is now built into Vagrant, it makes sense to me to ditch the folder, and move the Vagrantfile to the repo root. One can also do vagrant commands from the root, which I find handy.

2. The new dependency pretty much replaces this part of your setup script: `nohup nodejs app.js &> /var/log/lighterpack.log &` The systemd unit method will start the app after reboot. Because I added the nodemon dependency, nodemon will watch for file changes, and restart the app automatically. Nice handy hands-off approach.

I've been trying to figure out where I can help, but am not very familiar with this project's code yet, so I am just doing things I think are helpful as I familiarize myself with the program.

**Comment by jtarchie** [comment]
How about Docker?

**Comment by jtarchie** [comment]
In fact, it looks like you already do so.

https://github.com/galenmaly/lighterpack/commit/c2d80bef70c544c768dd106dcacad969e7307d14

**Comment by galenmaly** [comment]
Closing out old LighterPack PRs against the old master branch.

Apologies for the lack of communication on this PR in the past - a new contributing guideline is up at https://github.com/galenmaly/lighterpack/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
